---
title: "C28125 | Microsoft Docs"
ms.date: 11/15/2016
ms.prod: "visual-studio-dev14"
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords: 
  - "C28125"
helpviewer_keywords: 
  - "C28125"
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 6
author: corob-msft
ms.author: corob
manager: jillfra
---
# C28125
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

warning C28125: The function must be called from within a try/except block  
  
 The driver is calling a function that must be called from within a try/except block, such as [ProbeForRead](https://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](https://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](https://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## Example  
 The following code example generates this warning:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 The following code example avoids this warning:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```
